name: residencial_cocoon
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-160.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.1
  universal_html: ^2.2.3
  url_strategy: ^0.2.0
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  ionicons: ^0.2.2
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/menu.jpg
    - assets/images/fondo.png
